apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: attendance-prod
patches:
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: attendance-prod
