apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: attendance-dev
configMapGenerator:
  - name: db-env
    behavior: replace
    literals:
      - DB_URL=jdbc:mariadb://mariadb-statefulset-0.mariadb-service.attendance-dev.svc.cluster.local:3306/attendance?useUnicode=true&characterEncoding=utf8
patches:
  - path: spring-image-patch.yaml
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: attendance-dev
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: "/dev"
