apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - sealed-mariadb-secret.yaml
  - spring-service.yaml
  - spring-ingress.yaml
  - spring-deployment.yaml
  - sealed-spring-secret.yaml
  - pv-mariadb.yaml
