apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: louiswu2011/attendance-management:202607291526
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: spring-secret
            - configMapRef:
                name: db-env
